env: dev  # Active environment: "dev" or "prod"

dev:
  data:
    raw_s3_path: "s3://demo-bucket-f4t/dev/raw_data.csv"
    processed_path: "data/processed/dev_preprocessed_data.csv"
  model:
    type: "random_forest"
    hyperparameters:
      n_estimators: 50
      max_depth: 5

prod:
  data:
    raw_s3_path: "s3://demo-bucket-f4t/prod/raw_data.csv"
    processed_path: "data/processed/prod_preprocessed_data.csv"
  model:
    type: "random_forest"
    hyperparameters:
      n_estimators: 100
      max_depth: 10